all: ui

ui: edit_object.ui edit_comment.ui edit_layout.ui edit_source.ui edit_expression.ui edit_tile.ui
	pyuic4 edit_object.ui > ui_edit_object.py
	pyuic4 edit_comment.ui > ui_edit_comment.py
	pyuic4 edit_layout.ui > ui_edit_layout.py
	pyuic4 edit_source.ui > ui_edit_source.py
	pyuic4 edit_expression.ui > ui_edit_expression.py
	pyuic4 edit_tile.ui > ui_edit_tile.py
