#!/usr/bin/python

import subprocess
import os

print "starting"

file = open("ICONSLIST", 'r')

category_map = {"actions": "actions",
                "apps": "apps",
                "category": "categories",
                "device": "devices",
                "filesystems": "places",
                "mime": "mimetypes",
                "mimetypes": "mimetypes",
                "place": "places"}

log = open("icons/CONTENTS", 'w')

for line in file:
  line = line.replace("\n", "")
  (category, new, old) = line.split("\t")
  if new == "none":
    new = old
  
  find = subprocess.Popen(["find", "../Oxygen/theme/", "-name", old+".svg"], stdin=subprocess.PIPE, stdout=subprocess.PIPE)
  output = find.stdout.readline().rstrip("\n")
  small = None
  while "small" in output:
    small = output
    output = find.stdout.readline().rstrip("\n")
  if small is not None and output == "":
    output = small

  real_category = category_map[category]
  newname = "oxsc-" + real_category + "-" + new
  if output != "":
    os.system("cp "+ output +" icons/" + newname)
    os.system("gzip -f icons/"+newname)
    os.system("mv icons/"+newname+".gz icons/"+newname+".svgz")
    log.write(new +"\t" + old + "\t" + output + "\toxygen\n")
    for size in ["16", "22", "32", "64", "128"]:
      os.system("cp ../Oxygen/theme/oxygen/"+size+"x"+size+"/*/"+old+".png "+ " icons/" + "ox"+size+"-" + real_category + "-" + new +".png")

  elif output == "":
    find = subprocess.Popen(["find", "../kdeaccessibility/IconThemes/mono/scalable/", "-name", old+".svgz"], stdin=subprocess.PIPE, stdout=subprocess.PIPE)
    output = find.stdout.readline().rstrip("\n")
    if output != "":
      os.system("cp "+ output +" icons/" + newname)
      log.write(new +"\t" + old + "\t" + output + "\tmono\n")
    else:
      log.write(new +"\t" + old + "\tNONE\n")
